### ISSUE TITLE
Document connect strings for older versions of libpq

### ISSUE THREAD

**Issue by leondutoit** [begriffs/postgrest-docs#11]
Hi

I used the centos 6 build for release 0.3.2.0 on a RHEL 6 machine and started postgrest in the same way as the documentation describes (https://github.com/begriffs/postgrest-docs/blob/master/docs/install/server.md#running-the-server). 

Doing this, however, does not work. The service starts but as soon as one does a request it fails to connect to the db and returns a rather cryptic error message: `{"details":"missing \"=\" after \"postgres://db_owner@db-host:5432/db_name\" in connection info string\n","code":"","message":"Connection error"}`. 

After some discussion with @ruslantalpa on gitter he suggested that I use a different form of connection string. Turns out that passing the connection string like this `"host=hostname user=username port=5432 dbname=dbname"` to postgrest works fine.

I would like to do a pull request to make other users aware of this detail for centos 6 builds but I am not sure where this should fit into the documentation. One possibility would be to add a small subsection or a note in https://github.com/begriffs/postgrest-docs/blob/master/docs/install/server.md#running-the-server.

If you would like me to add this to the docs please let me know where.

cheers
Leon

**Comment by eradman** [comment]
The subject of this ticket should probably be "Document connect strings for PostgreSQL 8.4". The URL format for connection strings has been supported since 9.0, which was released a long time ago (September of 2010).

**Comment by leondutoit** [comment]
I don't agree with the change in the title - I am using PostgreSQL 9.4. I don't think this is about the db version.

**Comment by eradman** [comment]
I apologize if I misunderstood the problem. Can you try explaining again why the URL syntax didn't work? As far as I know there are no connection string options that cannot be expressed as a URL.

**Comment by leondutoit** [comment]
No worries :) I don't have a deep enough understanding of the source or the build environment (shared libraries) on Centos 6 to give an accurate diagnosis.

Everything that I observed, in terms of error messages, is documented in the original issue description. I was checking the PostgreSQL server logs at the time and didn't get anything from there - I was not reaching the server so I _assume_ the error message was generated by postgrest. 

Could it be that building postgrest on Centos 6 makes it depend on older versions of libpq?

**Comment by eradman** [comment]
That is possible. What does `ldd` say about which client library is used?

    $ ldd postgrest | grep libpq
        libpq.so.5 => /usr/pgsql-9.5/lib/libpq.so.5 (0x00007fcb4e33d000)

**Comment by leondutoit** [comment]
`libpq.so.5 => /usr/lib64/libpq.so.5 (0x0000003539a00000)` is what that returns.

**Comment by begriffs** [comment]
(Just remembered postgrest doesn't support postgresql older than 9.3, so yeah the title of this issue is inaccurate)

**Comment by eradman** [comment]
Try running `clean`/`build` again which your path modified to use the 9.4+ client:

    export PATH=/usr/pgsql-9.4/bin:$PATH

I don't know how exactly how `libpq` is discovered by this build, but I think this is all I had to do on CentOS 7.

**Comment by ruslantalpa** [comment]
@everyone
just like postgresql 8, centos 6 is also old --> the latest version of postgresql/libpq available for centos6 is 8+.
when compiling in centos6 you are compiling against libpq that understands only the old format of the connection string.
The title is not really correct because this connection string format has nothing to do with the version of  the db you are connecting to (you can connect to 9+ db from 8+ client), it has only to do with the version of the client that is trying to connect to the db.

**Comment by leondutoit** [comment]
I think the title reflects the situation now. Such documentation could probably just be a footnote to the main one, mentioning that RHEL and Centos 6 systems mostly use older versions of libpq and therefore require Postgrest to be started with a different form of connection string.  

I'll come up with a pull request soon.

**Comment by begriffs** [comment]
@leondutoit I'd love a PR if you're still interested. The docs have been rewritten and the relevant section is http://postgrest.com/en/v0.4/admin.html#configuration

To update it you'd open a PR against the v0.4 branch.

**Comment by leondutoit** [comment]
Sure thing, thanks for the pointer to the correct branch and location.
