### ISSUE TITLE
Calling a rpc procedure with array parameters

### ISSUE THREAD

**Issue by shanakadu** [begriffs/postgrest-docs#18]
HI,
I will only ask,  if is it  possible to make a request of a procedure with an array in parameters?

```
CREATE OR REPLACE FUNCTION public.test_array(input text[])
  RETURNS integer[] AS
$BODY$declare 
ret integer[];
val integer;
txt text;
begin


FOREACH txt in array  test_array.input
loop
 val = cast( txt as integer ) ;
 ret = array_append(ret,val);
end loop;
return ret;
end;$BODY$
```
Thanks

**Comment by begriffs** [comment]
Not directly. You could use an argument of type `json` and then check that it's a json array and loop through it that way.

**Comment by shanakadu** [comment]
Thanks @begriffs , it works!!.
 And if it helpfull for someone. And example how to works with it.

`CREATE OR REPLACE FUNCTION public.test_array(param_in json)
  RETURNS SETOF return_fourquadrants_getloadresource AS
$BODY$
--for test in pgsql cmd : select  * from test_array('[{"field1":3,"field2":5},{"field1":1,"field2":2}]');
--postgrest call, on body
--{
--    "param_in":[{"field1":3,"field2":5},{"field1":1,"field2":2}]
--}
declare
_rc  refcursor;
_r record;
_i type_struct;

begin
open _rc for select * from json_array_elements(test_array.param_in);
loop 
 fetch _rc into _r;
 exit when not found;

 RAISE NOTICE '%',to_json(_r.value);
_i = json_populate_record(null::type_struct, to_json(_r.value));
RAISE NOTICE 'ee %',_i;
return next _i;
end loop;
return ;
end;`

**Comment by begriffs** [comment]
Glad you got it working! Would you consider sending a pull request to add a note about how to deal with json arrays in function arguments? I think you're not the first person to ask. Maybe add it in this section if you'd be so kind https://github.com/begriffs/postgrest-docs/blob/master/docs/api/reading.md#stored-procedures
