### ISSUE TITLE
Promote 0.3.2 to be a first-class version in the docs

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest-docs#38]
At the bottom of the table of contents at postgrest.com there is a version number selector that shows all branches/tags with version numbers that I have marked as "active." If we port the v0.3.2 branch from markdown to restructured text then I can activate it as a version that is selectable. That's how new versions will be too, so it it would be consistent that way. There are many people who are not ready to upgrade to v0.4 because of its backward incompatible changes, and these people would like easy access to the docs.

@uniphil you said you'd like to send a pull request to fix up that branch?

To review your changes locally you can

1. [Install sphinx](http://www.sphinx-doc.org/en/stable/install.html) on your development machine.
2. `sphinx-build -b html -a -n . _build` then open `_build/index.html` in your browser.
3. Alternately `sphinx-autobuild -b html -a -n . _build` will run a temporary server on localhost which refreshes the browser on every change.

You'll want to add `_build` to .gitignore because it gets generated fresh on the Read The Docs server.

**Comment by phanimahesh** [comment]
`pandoc --from=markdown --to=rst` would be a good starting point IMO.
