### ISSUE TITLE
Verify a password against a SCRAM-SHA-256 hash

### ISSUE THREAD

**Issue by fjf2002** [begriffs/postgrest-docs#562]
Hello,

I once had postgrest running with "SQL user management" as described in https://postgrest.org/en/stable/auth.html#sql-user-management .

In the MD5 hashing days I even went one step further, not having a password hash in the described `basic_auth.users` table, but I used the MD5 password hash `rolpassword` from the `pg_catalog.pg_authid` table. I thought this is a nice idea, having the same password for plain database connections and the postgrest API.

Now MD5 is considered as too insecure, and SCRAM-SHA-256 is standard in the `pg_catalog.pg_authid` table. How can I acheive my goal with SCRAM?

This means in particular, how can I verify a plaintext password against a SCRAM-SHA-256 password hash stored in `pg_catalog.pg_authid.rolpassword`, using the `pgcrypto` extension?

**Comment by steve-chavez** [comment]
> If you are interested to add that into the docs, please let me know.

@fjf2002 That would be great! Please go ahead.

**Comment by fjf2002** [comment]
Gladly I will try that. Before that, some questions:
* Shall I edit/replace parts of the chapter "Storing users and passwords", or present a new chapter, as an alternative to the other chapter?
* If the latter shall happen: Should a chapter be added there or in the "how-to" section?
* The whole section depends on the idea of the email address being used in the authentication and the JWT. My whole issue is re-using the user's database password for postgrest authentication, which somehow would sound saner in conjunction with the sql user name (instead of the mail address) - what do you think?

**Comment by steve-chavez** [comment]
Hmm, at first I was thinking we could have it as a tabbed snippet like we do for HTTP/CURL snippets on https://postgrest.org/en/stable/api.html.

But as you mention, since it differs from the "Storing users and passwords" I think it would be better as a new "how-to".

**Comment by steve-chavez** [comment]
Solved on https://github.com/PostgREST/postgrest-docs/pull/581
