### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by Lellansin** [begriffs/postgrest-docs#66]
It would be helpful to have multi language version 😄 
Is there anything I can do? I'd like to contribute with it.

**Comment by begriffs** [comment]
[This page](https://wiki.haskell.org/Internationalization_of_Haskell_programs#Approaches_to_internationalization_in_Haskell) says there are a few ways to do internationalization in Haskell. Maybe GNU gettext would make it easiest for non-Haskellers to contribute translations.

Which things do you want to translate - just the error messages? If we also translate the config file options that might require maintaining different documentation pages per language.

**Comment by begriffs** [comment]
Oops, I thought this issue was filed on the main project, but you're talking specifically about documentation...

If we offer docs translations then I definitely need somebody to commit to keeping them up to date. I feel like the docs do not even have enough information in English, so I'm concerned about slowing them down even more.

**Comment by Lellansin** [comment]
Um, I get interested in this, and I'd like to study it by translate the docs (to Chinese). Due to your concern, I think I could do this job just in my fork. Hope you can help me if I got problem ;)  And while you think the English version has enough info, I'd like to start to PR. (feel free to close this)

**Comment by begriffs** [comment]
Thanks for volunteering to help!

It looks like the way to make a translation is to make a separate project on readthedocs.org, and then connect the main project to it. https://docs.readthedocs.io/en/latest/localization.html#project-with-multiple-translations

So you could make a project like "postgrest-cn" and I would link to you.

**Comment by Lellansin** [comment]
Yeah, that's clear. I've got it 🙆‍♂️

**Comment by begriffs** [comment]
Have you written a translation yet that you would like me to link?

**Comment by Lellansin** [comment]
@begriffs  Sure, I did some translation but forget to commit. And I got some problem while try to publish on readthedocs today (https://readthedocs.org/projects/postgrest-docs-chinese/builds/5666814/). Well you reminder me, I'll keep on translate this in the several days 🚀 .

**Comment by Lellansin** [comment]
fixed encoding problem, link http://postgrest-docs-chinese.readthedocs.io/en/latest/

**Comment by begriffs** [comment]
Thank you, you rock!

I'm trying to set your project as a translation of mine, but Read The Docs says, "Both projects have a language of `en`. Please choose one with another language" Can you update the language in your project's settings?

**Comment by Lellansin** [comment]
done~ New link: http://postgrest-docs-chinese.readthedocs.io/zh/latest/

**Comment by begriffs** [comment]
That worked! It's now active at https://postgrest.com/zh/latest/index.html
