### ISSUE TITLE
intro.rst: 404 to angular2-postgrest

### ISSUE THREAD

**Issue by elimisteve** [begriffs/postgrest-docs#67]
This project no longer exists: https://github.com/PierreRochard/angular2-postgrest

Linking to https://github.com/PierreRochard/postgrest-angular or even https://github.com/PierreRochard/postgrest-boilerplate may be a suitable replacement?

**Comment by PierreRochard** [comment]
Oh boy I didn't realize I was being linked to! I changed the repo name after Angular 4 came out 😬. I wasn't going to request a link until these repos stabilized and had docs, very much an "alpha preview" right now!

postgrest-angular iterates over the OpenAPI/swagger document and generates the UI.
postgrest-boilerplate is for creating an auth backend (mostly copy/pasted from the docs) and ancillary tables that postgrest-angular will use to save users' UI settings.

**Comment by begriffs** [comment]
I updated the links.
