### ISSUE TITLE
binary is xz not gzip

### ISSUE THREAD

**Issue by tarpdalton** [begriffs/postgrest-docs#72]
On rhel7 I had to use this:
`tar Jxf postgrest-0.4.1.0-centos.tar.xz`
Instead of this (from [install doc](https://github.com/begriffs/postgrest-docs/blob/v0.4/install.rst)):
`tar zxf postgrest-[version]-[platform].tar.xz`

I'm not a unix wizard so I could be missing something

**Comment by begriffs** [comment]
Oh you're right, J is the right option for xz. Want to send a PR?
